### ISSUE TITLE
Find a way to make the Instruction Text on white background!

### ISSUE THREAD

**Issue by dottenbr** [newmatik/Quality#16]

**Comment by emakis** [comment]
done, waiting for banch update to work on production server

**Comment by dottenbr** [comment]
Unfortunately it is not yet 100% resolved. Please check, from copying the old content from the previous by copy and paste you have the grey background. Please do search and remove to remove this from all instructions manually.

![unbenannt](https://cloud.githubusercontent.com/assets/9136094/14200918/a00f0ab4-f7ee-11e5-9db0-8f2ce378d7f9.png)

**Comment by emakis** [comment]
When copy text that is pasted with its styling as inline styling in the new document's html. Inline styling always is stronger than any class assigned to objects.
For now I have recreated all texts with a white background, and did all bolds, lists etc for this document. I hope no further decorating will be needed. Best practice is to copy-paste pure text and all stylings could be applied into the document's page

**Comment by dottenbr** [comment]
Makis, I really do not like opening tickets many times again. You did NOT resolve this:

https://www.newmatik.com/desk#Form/Instruction/LED%20Polung%20Erkennen%20und%20Pr%C3%BCfen
https://www.newmatik.com/desk#Form/Instruction/Handbest%C3%BCckung%20von%20SMT%20Bauteilen

And more that are still grey.

**Comment by dottenbr** [comment]
Do not create it with white background, that is crazy. Create it with no background and if the styling is done while saving the document please fix the fucked up code that does that. Manually applying white background instead of grey is totally crazy.
